name: "AUTO"
on:
  push:
    paths:
      - '.github/workflows/Auto.yml'
      - 'Account.md'
jobs:
  build:
    name: 'Add...'
    if: github.repository == 'kakathic/ZH-VN' && github.ref == 'refs/heads/ZH'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Process
        run: |
          # kakathic
          
