name: CI
on:
 push:
  branches:
      - Vip
 pull_request:
  branches:
      - Vip
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tự động hóa
        run: |
          echo 123
          chmod 777 install.sh
          . install.sh
      - name: Tải lên
         uses: softprops/action-gh-release@v1
         with:
          tag: ${{ github.ref_name }}
          tag_name: Test-${{ github.ref_name }}
          files: 1.zip
          prerelease: true
          generate_release_notes: true
