name: CI
on:
  push:
    branches: [ "Vip" ]
  pull_request:
    branches: [ "Vip" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tự động hóa
        run: |
          sudo
          sudo -c ls /data
          cp -rf install.sh /data/install.sh
          chmod 777 /data/install.sh
          . /data/install.sh
