# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Đánh dấu các vấn đề cũ và yêu cầu kéo

on:
  schedule:
  - cron: '37 13 1 * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Thông báo sự cố cũ'
        stale-pr-message: 'Thông báo yêu cầu kéo cũ'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
