name: "Mod Thời Tiết"
on:
  workflow_dispatch:
  push:
    paths:
      - 'Hpk/com.miui.weather2.apk'
jobs:
  build:
    name: 'Quá trình thực hiện'
    if: github.repository == 'kakathic/ZH-VN' && github.ref == 'refs/heads/ZH'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Chạy Code
        run: |
          # kakathic
          . .github/ThoiTiet.sh
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          name: Tool
          tag_name: Package
          files: Up/*
          prerelease: true
          generate_release_notes: true

